import "./globals.css";
// next.js fonts
import { barlow } from "@/lib/fonts";

// custom components
import MainHeader from "@/components/rootLayout/main-header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} bg-primary-black`}>
        <MainHeader />
          {children}
        <div id="aside" className="md:hidden"></div>
      </body>
    </html>
  );
}
